name: "Update Workflow Templates"

on:
  push:
    branches:
      - master

jobs:
  workflow-templates-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    - name: Pushes to another repository
      if: ${{ git diff --quiet HEAD^ HEAD -- workflow-templates/ }}
      uses: ./push-to-other-repositories/action
      env:
        API_TOKEN_GITHUB: ${{ secrets.WORKFLOWTEMPLATESTESTENV_APP_CLIENT_SECRET }}
      with:
        source-directory: 'workflow-templates'
        # destination-github-username: '<dest-user>'
        # destination-repository-name: '<dest-repo'