name: "Update Workflow Templates"

on:
  push:
    branches:
      - master

jobs:
  workflow-templates-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - run: git diff --quiet HEAD^ HEAD -- workflow-templates/ || echo True > TEMPLATES_CHANGED
    # Really need to find a way to put a condition in front of this next action. 

    - name: Pushes to another repository
      # if: ${{ git diff --quiet HEAD^ HEAD -- workflow-templates/ }}
      uses: ./.github/actions/action
      env:
        API_TOKEN_GITHUB: ${{ secrets.WORKFLOWTEMPLATESTESTENV_APP_CLIENT_SECRET }}
      with:
        source-directory: 'workflow-templates'
        # destination-github-username: '<dest-user>'
        # destination-repository-name: '<dest-repo'