name: "Update Workflow Templates"

on:
  push:
    branches:
      - master

jobs:
  workflow-templates-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Obtain GitHub App Installation Access Token
      id: githubAppAuth
      run: |
       TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
       echo "::add-mask::$TOKEN"
       echo "::set-output name=token::$TOKEN"
   - name: Use the obtained token
     run: |
       curl -X POST -H 'Content-Type: application/json' \
         -d '{"context":"test","state":"success"}' \
         "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
     env:
       GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}

  
    - name: Pushes to another repository
      uses: WorkFlowTemplatesTestEnv/.github/.github/actions/push-to-other-repository@master
      env:
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY}}
        #PI_TOKEN_GITHUB: ${{ secrets.WORKFLOWTEMPLATESTESTENV_APP_CLIENT_SECRET }}
      with:
        source-directory: 'workflow-templates'

# if: ${{ git diff --quiet HEAD^ HEAD -- workflow-templates/ }}
# - run: git diff --quiet HEAD^ HEAD -- workflow-templates/ || echo True > TEMPLATES_CHANGED
# Really need to find a way to put a condition in front of this next action. 
