name: "Update Workflow Templates"

on:
  push:
    branches:
      - master

jobs:
  workflow-templates-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Pushes to another repository
      uses: ./.github/actions/push-to-other-repository/action
      env:
        API_TOKEN_GITHUB: ${{ secrets.WORKFLOWTEMPLATESTESTENV_APP_CLIENT_SECRET }}
      with:
        source-directory: 'workflow-templates'

# if: ${{ git diff --quiet HEAD^ HEAD -- workflow-templates/ }}
# - run: git diff --quiet HEAD^ HEAD -- workflow-templates/ || echo True > TEMPLATES_CHANGED
# Really need to find a way to put a condition in front of this next action. 
